{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "robotlb.fullname" . }}-cr
rules:
 {{- if .Values.serviceAccount.permissions -}}
 {{ toYaml .Values.serviceAccount.permissions | nindent 2 }}
 {{- else }}
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
 {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "robotlb.fullname" . }}-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "robotlb.fullname" . }}-cr
subjects:
  - kind: ServiceAccount
    name: {{ include "robotlb.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
